# Generated by Django 2.1.7 on 2019-03-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(verbose_name='bin timestamp')),
                ('sample_time', models.DateTimeField(verbose_name='sample time')),
                ('latitude', models.FloatField(default=-9999)),
                ('longitude', models.FloatField(default=-9999)),
                ('depth', models.FloatField(default=0)),
                ('qc_bad', models.BooleanField(default=False)),
                ('temperature', models.FloatField(default=-9999)),
                ('humidity', models.FloatField(default=-9999)),
                ('run_time', models.FloatField(default=-9999)),
                ('ml_analyzed', models.FloatField(default=-9999)),
            ],
        ),
        migrations.CreateModel(
            name='DataDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('kind', models.CharField(default='raw', max_length=32)),
                ('priority', models.IntegerField(default=1)),
                ('last_synced', models.DateTimeField(verbose_name='time of last db sync')),
                ('whitelist', models.CharField(default='data', max_length=512)),
                ('blacklist', models.CharField(default='skip,bad', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='datadirectory',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='dashboard.Dataset'),
        ),
        migrations.AddField(
            model_name='bin',
            name='datasets',
            field=models.ManyToManyField(related_name='bins', to='dashboard.Dataset'),
        ),
    ]
