# Generated by Django 2.1.7 on 2019-03-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190329_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadirectory',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time of last db sync'),
        ),
    ]
