# Generated by Django 2.1.7 on 2019-03-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190329_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='pid',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
