# Generated by Django 2.1.7 on 2019-03-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_bin_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='look_time',
            field=models.FloatField(default=-9999),
        ),
    ]
