# Generated by Django 2.1.7 on 2019-03-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_bin_look_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='qc_no_rois',
            field=models.BooleanField(default=False),
        ),
    ]
