# Generated by Django 2.1.7 on 2019-03-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_bin_qc_no_rois'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='metadata',
            field=models.CharField(default='{}', max_length=8192),
        ),
    ]
