# Generated by Django 2.1.7 on 2019-04-12 16:17

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_bin_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='longitude',
        ),
        migrations.AddField(
            model_name='bin',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(), srid=4326),
        ),
    ]
