# Generated by Django 2.1.7 on 2019-04-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190412_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('version', models.IntegerField(default=2)),
                ('nickname', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=64)),
                ('_password', models.CharField(db_column='password', max_length=128)),
                ('share_name', models.CharField(default='Data', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bins', to='dashboard.Instrument'),
        ),
    ]
