# Generated by Django 2.1.7 on 2019-04-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190419_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
