# Generated by Django 2.1.7 on 2019-04-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190419_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadirectory',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
