# Generated by Django 2.1.7 on 2019-04-23 17:17

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_datadirectory_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-9999, -9999, srid=4326), srid=4326),
        ),
    ]
