# Generated by Django 2.1.7 on 2019-04-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20190423_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='concentration',
            field=models.FloatField(default=-9999),
        ),
        migrations.AddField(
            model_name='bin',
            name='n_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bin',
            name='n_triggers',
            field=models.IntegerField(default=0),
        ),
    ]
