# Generated by Django 2.1.7 on 2019-05-02 20:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20190426_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
