# Generated by Django 2.1.7 on 2019-05-04 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190502_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TagEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Bin')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='tags',
            field=models.ManyToManyField(through='dashboard.TagEvent', to='dashboard.Tag'),
        ),
    ]
