# Generated by Django 2.1.7 on 2019-05-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20190505_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='metadata',
            new_name='metadata_json',
        ),
        migrations.AlterField(
            model_name='bin',
            name='metadata_json',
            field=models.CharField(db_column='metadata', default='{}', max_length=8192),
        ),
    ]
