# Generated by Django 2.1.7 on 2019-05-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20190508_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='concentration',
            field=models.FloatField(default=-9999999),
        ),
        migrations.AlterField(
            model_name='bin',
            name='humidity',
            field=models.FloatField(default=-9999999),
        ),
        migrations.AlterField(
            model_name='bin',
            name='look_time',
            field=models.FloatField(default=-9999999),
        ),
        migrations.AlterField(
            model_name='bin',
            name='ml_analyzed',
            field=models.FloatField(default=-9999999),
        ),
        migrations.AlterField(
            model_name='bin',
            name='run_time',
            field=models.FloatField(default=-9999999),
        ),
        migrations.AlterField(
            model_name='bin',
            name='temperature',
            field=models.FloatField(default=-9999999),
        ),
    ]
