# Generated by Django 2.1.7 on 2019-05-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20190528_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
