# Generated by Django 2.1.7 on 2019-07-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_dataset_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='nickname',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
