# Generated by Django 2.1.7 on 2019-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20190706_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='_password',
            field=models.CharField(blank=True, db_column='password', max_length=128),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='share_name',
            field=models.CharField(blank=True, default='Data', max_length=128),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='username',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
