# Generated by Django 2.1.7 on 2019-07-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20190708_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadirectory',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
