# Generated by Django 2.1.7 on 2019-08-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20190805_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='timeout',
            field=models.IntegerField(default=30),
        ),
    ]
