# Generated by Django 2.1.7 on 2019-08-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_instrument_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='skip',
            field=models.BooleanField(default=False),
        ),
    ]
