# Generated by Django 2.1.7 on 2019-09-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_bin_skip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='sample_time',
            field=models.DateTimeField(db_index=True, verbose_name='sample time'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='bin timestamp'),
        ),
    ]
