# Generated by Django 2.1.7 on 2019-09-19 14:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20190906_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='depth',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
