# Generated by Django 2.1.7 on 2019-09-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20190919_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='depth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='depth',
            field=models.FloatField(null=True),
        ),
    ]
