# Generated by Django 2.1.7 on 2019-11-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_dataset_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='attribution',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='dataset',
            name='funding',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
