# Generated by Django 2.1.7 on 2019-11-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20191108_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='cast',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='bin',
            name='cruise',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='bin',
            name='niskin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='sample_type',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
