# Generated by Django 4.2.11 on 2024-07-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20191114_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinDatasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dashboard_bin_datasets',
                'managed': False,
            },
        ),
    ]
