# Generated by Django 4.2.14 on 2024-10-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20191114_2039'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='datadirectory',
            constraint=models.UniqueConstraint(fields=('dataset', 'path'), name='unique path'),
        ),
    ]
