# Generated by Django 3.0.3 on 2020-03-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20191114_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='netbios_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
