# Generated by Django 4.2.14 on 2024-10-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20191114_2039'),
    ]

    operations = [
        # This constraint has been intentionally commented out because it was too restrictive and prevented users with
        #   existing data from running migrations. A follow-up migration (0038) has been made to create this constraint
        #   with an additional field, kind, so this one is no longer necessary
        # migrations.AddConstraint(
        #     model_name='datadirectory',
        #     constraint=models.UniqueConstraint(fields=('dataset', 'path'), name='unique path'),
        # ),
    ]
