# Generated by Django 4.2.14 on 2024-09-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20191114_2039'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='datadirectory',
            constraint=models.UniqueConstraint(fields=('path',), name='unique path'),
        ),
    ]
