# Generated by Django 4.2.14 on 2024-11-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_datadirectory_unique_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_latitude', models.FloatField(default=41.5507768)),
                ('default_longitude', models.FloatField(default=-70.6593102)),
                ('default_zoom_level', models.IntegerField(default=6)),
            ],
        ),
    ]
