# Generated by Django 4.2.17 on 2025-02-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_appsettings'),
    ]

    operations = [
        # A prior constraint existed, but may have failed for some users running migrations. The use of direct SQL
        #   here is to handle those scenarios, and only drop the constraint if it already exists
        migrations.RunSQL("ALTER TABLE dashboard_datadirectory DROP CONSTRAINT IF EXISTS \"unique path\""),
        migrations.AddConstraint(
            model_name='datadirectory',
            constraint=models.UniqueConstraint(fields=('dataset', 'path', 'kind'), name='unique path'),
        ),
    ]
