# Generated by Django 4.2.20 on 2025-04-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_remove_datadirectory_unique_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadirectory',
            name='require_roi_files',
            field=models.BooleanField(default=True),
        ),
    ]
