# Generated by Django 4.2.21 on 2025-07-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_team_teamuser_teamdataset_team_datasets_team_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
