# Generated by Django 4.2.20 on 2025-05-11 15:05

from django.db import migrations


def apply_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Group = apps.get_model('auth', 'Group')
    Group.objects.using(db_alias).bulk_create([
        Group(id=7, name="Manager"),
    ])

def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name="Manager").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_dataset_is_private'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
