# Generated by Django 4.2.21 on 2025-07-18 02:47

from django.db import migrations
from common.constants import Features


def apply_migration(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.update_or_create(
        name=Features.TEAMS.value,
        defaults={
            'active': False,
            'note': 'Enables the teams feature'
        }
    )

def revert_migration(apps, schema_editor):
    try:
        Switch = apps.get_model('waffle', 'Switch')
        Switch.objects.filter(name=Features.TEAMS.value).delete()
    except LookupError:
        # Waffle isn't installed
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_teamuser_is_manager'),
        ('waffle', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
