# Generated by Django 4.2.21 on 2025-06-06 19:14

from django.db import migrations


def apply_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Group = apps.get_model('auth', 'Group')
    Group.objects.using(db_alias).bulk_create([
        Group(id=5, name="Admin"),
        Group(id=6, name="User"),
    ])

def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name="Admin").delete()
    Group.objects.filter(name="User").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_team_teamuser_teamdataset_team_datasets_team_users'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
