# Generated by Django 4.2.21 on 2025-06-06 19:21

from django.db import migrations


def apply_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')

    users_without_groups = User.objects.filter(groups__isnull=True)
    admin_group = Group.objects.get(name="Admin")
    user_group = Group.objects.get(name="User")

    for user in users_without_groups:
        if user.is_superuser:
            user.groups.add(admin_group)
        else:
            user.groups.add(user_group)

def revert_migration(apps, schema_editor):
    # Do not revert anything - there is no guarantee of which records were added when
    #   migrating, so it's safer to leave them in place on the off chance the migration
    #   needs to be reverted
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_auto_20250606_1914'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
