# Generated by Django 4.2.21 on 2025-07-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_add_initial_groups_20250606_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
