# Generated by Django 4.2.21 on 2025-07-18 03:46

from django.db import migrations
from common.constants import TeamRoles


def apply_migration(apps, schema_editor):
    TeamRole = apps.get_model('dashboard', 'TeamRole')
    TeamRole.objects.bulk_create([
        TeamRole(id=TeamRoles.CAPTAIN.value, name="Captain"),
        TeamRole(id=TeamRoles.MANAGER.value, name="Manager"),
        TeamRole(id=TeamRoles.USER.value, name="User"),
    ])

def revert_migration(apps, schema_editor):
    TeamRole = apps.get_model('dashboard', 'TeamRole')
    TeamRole.objects.filter(id__in=[
        TeamRoles.CAPTAIN.value,
        TeamRoles.MANAGER.value,
        TeamRoles.USER.value
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_teamrole_remove_teamuser_is_manager'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
