# Generated by Django 4.2.21 on 2025-07-18 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20250718_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamuser',
            name='role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='dashboard.teamrole'),
        ),
    ]
