# Generated by Django 4.2.21 on 2025-08-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20250721_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='data_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.datadirectory'),
        ),
        migrations.AddField(
            model_name='bin',
            name='path',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
