# Generated by Django 4.2.22 on 2025-09-17 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_dataset_contact_email_dataset_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.team'),
        ),
    ]
