# Generated by Django 4.2.26 on 2026-01-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.SlugField(),
        ),
    ]
