# Generated by Django 4.2.26 on 2026-02-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
