# Generated by Django 4.2.28 on 2026-02-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_team_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
