# Generated by Django 4.2.29 on 2026-03-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_team_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
