# Generated by Django 4.2.29 on 2026-04-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_team_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadirectory',
            name='is_class_score_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datadirectory',
            name='model',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
