# Generated by Django 4.2.30 on 2026-04-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_bin_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='accessioned',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
