# Generated by Django 4.2.28 on 2026-03-25 12:00

from django.db import migrations


def convert_newlines_to_br(apps, schema_editor):
    Dataset = apps.get_model('dashboard', 'Dataset')
    Team = apps.get_model('dashboard', 'Team')
    
    # Convert Dataset descriptions
    for dataset in Dataset.objects.exclude(description__isnull=True).exclude(description=''):
        if '<' not in dataset.description:
            dataset.description = dataset.description.replace('\n', '<br />')
            dataset.save(update_fields=['description'])
    
    # Convert Team descriptions
    for team in Team.objects.exclude(description__isnull=True).exclude(description=''):
        if '<' not in team.description:
            team.description = team.description.replace('\n', '<br />')
            team.save(update_fields=['description'])


def reverse_br_to_newlines(apps, schema_editor):
    Dataset = apps.get_model('dashboard', 'Dataset')
    Team = apps.get_model('dashboard', 'Team')
    
    # Reverse Dataset descriptions
    for dataset in Dataset.objects.exclude(description__isnull=True).exclude(description=''):
        dataset.description = dataset.description.replace('<br />', '\n').replace('<br>', '\n')
        dataset.save(update_fields=['description'])
    
    # Reverse Team descriptions
    for team in Team.objects.exclude(description__isnull=True).exclude(description=''):
        team.description = team.description.replace('<br />', '\n').replace('<br>', '\n')
        team.save(update_fields=['description'])


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_bin_modified'),
    ]

    operations = [
        migrations.RunPython(
            convert_newlines_to_br,
            reverse_code=reverse_br_to_newlines
        ),
    ]
