# Generated by Django 4.2.30 on 2026-04-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_datadirectory_is_class_score_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadirectory',
            name='model',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
    ]
